-- SQL Server 2022 schema for the client compatibility test suite.
-- All tables live in the default dbo schema.
-- Engine notes:
--   boolean  → BIT              (0/1; coerced to bool by the result layer)
--   text[]   → NVARCHAR(MAX)    (JSON arrays; looksLikeJSON heuristic handles JSON)
--   serial   → INT IDENTITY(1,1)
--   UUID PK  → UNIQUEIDENTIFIER DEFAULT NEWID()
--   FTS      → SQL Server FULLTEXT catalog + FULLTEXT INDEX on todos.task
--
-- Named PRIMARY KEY constraints are required so the FULLTEXT INDEX creation can
-- reference the key index by a stable, known name.

-- Full-text catalog.
IF NOT EXISTS (SELECT 1 FROM sys.fulltext_catalogs WHERE name = N'CompatCatalog')
    CREATE FULLTEXT CATALOG CompatCatalog AS DEFAULT;
GO

-- todos
IF OBJECT_ID('dbo.todos', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.todos (
        id   INT           NOT NULL IDENTITY(1,1),
        done BIT           NOT NULL DEFAULT 0,
        task NVARCHAR(500) NOT NULL,
        due  DATE          NULL,
        tags NVARCHAR(MAX) NOT NULL DEFAULT N'[]',
        CONSTRAINT PK_todos    PRIMARY KEY (id),
        CONSTRAINT UQ_todos_task UNIQUE (task)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.fulltext_indexes fi
    JOIN sys.objects o ON o.object_id = fi.object_id
    WHERE o.name = N'todos' AND o.type = 'U'
)
BEGIN
    CREATE FULLTEXT INDEX ON dbo.todos (task)
        KEY INDEX PK_todos ON CompatCatalog
        WITH CHANGE_TRACKING AUTO;
END;
GO

-- persons
IF OBJECT_ID('dbo.persons', 'U') IS NULL
CREATE TABLE dbo.persons (
    id    INT           NOT NULL IDENTITY(1,1),
    name  NVARCHAR(255) NOT NULL,
    age   INT           NULL,
    email NVARCHAR(255) NULL,
    CONSTRAINT PK_persons     PRIMARY KEY (id),
    CONSTRAINT UQ_persons_email UNIQUE (email)
);
GO

-- assignments
IF OBJECT_ID('dbo.assignments', 'U') IS NULL
CREATE TABLE dbo.assignments (
    id        INT NOT NULL IDENTITY(1,1),
    person_id INT NULL,
    todo_id   INT NULL,
    CONSTRAINT PK_assignments       PRIMARY KEY (id),
    CONSTRAINT UQ_assignments       UNIQUE (person_id, todo_id),
    CONSTRAINT FK_assign_person     FOREIGN KEY (person_id) REFERENCES dbo.persons(id) ON DELETE CASCADE,
    CONSTRAINT FK_assign_todo       FOREIGN KEY (todo_id)   REFERENCES dbo.todos(id)   ON DELETE CASCADE
);
GO

-- channels
IF OBJECT_ID('dbo.channels', 'U') IS NULL
CREATE TABLE dbo.channels (
    id   INT           NOT NULL IDENTITY(1,1),
    slug NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_channels  PRIMARY KEY (id),
    CONSTRAINT UQ_channels_slug UNIQUE (slug)
);
GO

-- messages
IF OBJECT_ID('dbo.messages', 'U') IS NULL
CREATE TABLE dbo.messages (
    id         INT           NOT NULL IDENTITY(1,1),
    message    NVARCHAR(MAX) NULL,
    channel_id INT           NULL,
    person_id  INT           NULL,
    CONSTRAINT PK_messages         PRIMARY KEY (id),
    CONSTRAINT FK_msg_channel      FOREIGN KEY (channel_id) REFERENCES dbo.channels(id),
    CONSTRAINT FK_msg_person       FOREIGN KEY (person_id)  REFERENCES dbo.persons(id)
);
GO

-- countries
IF OBJECT_ID('dbo.countries', 'U') IS NULL
CREATE TABLE dbo.countries (
    id   INT           NOT NULL IDENTITY(1,1),
    name NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_countries    PRIMARY KEY (id),
    CONSTRAINT UQ_countries_name UNIQUE (name)
);
GO

-- cities
IF OBJECT_ID('dbo.cities', 'U') IS NULL
CREATE TABLE dbo.cities (
    id         INT           NOT NULL IDENTITY(1,1),
    name       NVARCHAR(255) NOT NULL,
    country_id INT           NULL,
    CONSTRAINT PK_cities           PRIMARY KEY (id),
    CONSTRAINT FK_city_country     FOREIGN KEY (country_id) REFERENCES dbo.countries(id)
);
GO

-- movies (UUID PK generated by DB)
IF OBJECT_ID('dbo.movies', 'U') IS NULL
CREATE TABLE dbo.movies (
    id           UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    name         NVARCHAR(255)    NOT NULL,
    tags         NVARCHAR(MAX)    NOT NULL DEFAULT N'[]',
    release_date DATE             NULL,
    watched_at   DATETIME2        NULL,
    CONSTRAINT PK_movies PRIMARY KEY (id)
);
GO

-- companies
IF OBJECT_ID('dbo.companies', 'U') IS NULL
CREATE TABLE dbo.companies (
    id      INT           NOT NULL IDENTITY(1,1),
    name    NVARCHAR(255) NOT NULL,
    address NVARCHAR(255) NULL,
    phone   NVARCHAR(50)  NULL,
    CONSTRAINT PK_companies PRIMARY KEY (id)
);
GO

-- people
IF OBJECT_ID('dbo.people', 'U') IS NULL
CREATE TABLE dbo.people (
    id         INT           NOT NULL IDENTITY(1,1),
    name       NVARCHAR(255) NOT NULL,
    age        INT           NULL,
    company_id INT           NULL,
    CONSTRAINT PK_people            PRIMARY KEY (id),
    CONSTRAINT FK_people_company    FOREIGN KEY (company_id) REFERENCES dbo.companies(id)
);
GO

-- items (accessible via Accept-Profile: private; same dbo schema)
IF OBJECT_ID('dbo.items', 'U') IS NULL
CREATE TABLE dbo.items (
    id   INT           NOT NULL IDENTITY(1,1),
    name NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_items PRIMARY KEY (id)
);
GO

-- RPC stored procedures (NativeRPC=true; discovered from sys.objects).
-- Scalar procs return a single column named after the proc so renderCall detects
-- them as scalar: len(cols)==1 && cols[0]==fnName heuristic.

IF OBJECT_ID('dbo.add', 'P') IS NOT NULL DROP PROCEDURE dbo.add;
GO
CREATE PROCEDURE dbo.add
    @a INT,
    @b INT
AS
    SELECT @a + @b AS [add];
GO

IF OBJECT_ID('dbo.get_todos_count', 'P') IS NOT NULL DROP PROCEDURE dbo.get_todos_count;
GO
CREATE PROCEDURE dbo.get_todos_count
AS
    SELECT CAST(COUNT(*) AS INT) AS [get_todos_count] FROM dbo.todos;
GO

IF OBJECT_ID('dbo.get_person_by_name', 'P') IS NOT NULL DROP PROCEDURE dbo.get_person_by_name;
GO
CREATE PROCEDURE dbo.get_person_by_name
    @name_param NVARCHAR(255)
AS
    SELECT id, name, age, email FROM dbo.persons WHERE name = @name_param;
GO
